### ISSUE TITLE
05 Nov 2018 Tech Talk: Discussion of The Effective Engineer

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#21]
@monfresh  will talk about Edmund Lau's _The Effective Engineer_ (https://www.effectiveengineer.com/).

@davemcorwin I'm listing you as MC until I hear otherwise.

**Comment by tadhg-ohiggins** [comment]
Changed the date to be TBD since this isn't happening on the original date of 22 Oct 2018.

**Comment by davemcorwin** [comment]
Video! https://drive.google.com/open?id=1q5rOgfHOF7X0e6l5vmo8gOg3SXr1dmNY
