### ISSUE TITLE
15 Oct 2018 Tech Talks Lite

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#23]
- [x] @mgwalker on Snyk.
- [x] @pburkholder on cloud.gov demos with demo-magic (or the cloud.gov meta-demo).
- [ ] Up for grabs.
- [ ] Up for grabs.
- [ ] Upload recording.

@tadhg-ohiggins will MC these.

**Comment by pburkholder** [comment]
@pburkholder on cloud.gov demos with demo-magic (or the cloud.gov meta-demo) 👍 ??

**Comment by tadhg-ohiggins** [comment]
@pburkholder I've added you to the list, thanks for the reminder!

**Comment by saracope** [comment]
Is there a recording or slide deck for this? Looking for info on Snyk. @pburkholder @davemcorwin 
Thanks!

**Comment by mgwalker** [comment]
Here's the deck on Snyk:  https://docs.google.com/presentation/d/1hJBtx4L7mXsUxNuD0JHzZ_kyjKt7FKXVn6SYmoqxo8c/edit#slide=id.p

Also feel free to ping me on Slack @mgwalker.  I'm not an expert but I'm happy to help if I can.  :)
