### ISSUE TITLE
Add links to appropriate Google Drive locations, add slide upload instructions to workflow for talks

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#24]
This is the parent folder, AFAICT:
https://drive.google.com/open?id=0B5fn0WMJaYDnfl9mRWdxVkxGU3ZqNDg0QzlQZ1plTUxLaVRIdURmOTZHNVlOZHlhaldjWTg

**Comment by davemcorwin** [comment]
added a link to the google drive folder in the tech talk issue template
