### ISSUE TITLE
Is this still the repo to schedule talks?

### ISSUE THREAD

**Issue by eddietejeda** [18F/tech-talks#29]
The content on this repo does not appear to be current. Is this where coordination still happens?

**Comment by tadhg-ohiggins** [comment]
We primarily use the issues, not the contents of the repo, to handle scheduling. Coordination normally happens in the #tech-talks channel on Slack, and issues are usually posted once times/subjects/etc. have been set.

**Comment by tadhg-ohiggins** [comment]
Now that we've been using the new approach for a while, and the README and other files have been updated to reflect the new way to schedule talks, I'm closing this issue.
