### ISSUE TITLE
 28 Jan 2019 Tech Talk: Stack-Agnostic End-to-End Testing with Jest and Puppeteer

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#30]
For web applications, why does our testing stack change when moving from language to language, when our users are using the same browsers to access them? The Chrome team has done quite a bit of work to make testing in a real browser within reach — and this talk covers how to use it for stable and fast end-to-end tests, executable in any environment.

@adunkman will present
@davemcorwin will MC

- [ ] Secure Zoom Pro Account
- [ ] Upload Video

**Comment by adunkman** [comment]
[Slides](https://speakerdeck.com/adunkman/stack-agnostic-end-to-end-testing-with-jest-and-puppeteer-at-18f) and [video](https://drive.google.com/drive/u/0/folders/1OXydrHm1aRMX768XBxvKGLC1-hwMa19g)!
