### ISSUE TITLE
25 Feb 2019 Tech Talks Lite #28

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#31]
- [x] @mheadd **Building a rules engine in CouchDB with JavaScript & HTTP**
This talk will provide a brief overview and introduction to CouchDB, an open source, document-oriented database maintained by the Apache foundation. It will introduce some core concepts of CouchDB, and provide a more in depth discussion of some of the features of CouchDB that make it attractive as a potential platform for a rules engine for federated data collection and service/benefit eligibility determination. Spoiler alert: there will be live coding.

- [x] @davemcorwin **Using an API as a data source in the Gatsby static site generator**
(might need help coming up with a better name!)

- [x] Decks, video, audio uploaded to GDrive:

**Comment by mheadd** [comment]
@davemcorwin How much time is typically allotted for each talk?

**Comment by tadhg-ohiggins** [comment]
@mheadd @davemcorwin Since last Monday was a holiday and next Monday (25 February) doesn't seem to yet have any talks assigned, shall we move these to Monday? (Apologies for not noticing the problem with the holiday in advance…)

**Comment by mheadd** [comment]
@tadhg-ohiggins That works for me.

**Comment by davemcorwin** [comment]
@tadhg-ohiggins ack! sounds good, I need to put mine together! Thanks for being on this.

**Comment by mheadd** [comment]
Thanks again for the opportunity to present!
