### ISSUE TITLE
Add Issue template?

### ISSUE THREAD

**Issue by adunkman** [18F/tech-talks#32]
It seems like a lot of these issues follow a similar template, including a checklist of things at the end to prepare for the tech talk. 

I’d like to add a step to that checklist (securing a phone number for Zoom meetings, so FedRelay interpreters can provide services when required). 

Any qualms with an issue template on GitHub? Or, is there another place that should be?

**Comment by tadhg-ohiggins** [comment]
@adunkman Sounds like a good idea to me!

**Comment by davemcorwin** [comment]
@adunkman sounds good, I don't think we're even using a template right now. 

I'm fairly sure that we do get a call-in number with the Zoom meeting now, its just not shared on the meeting invite so maybe I can track that down to do that.
